services:
  yorobot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot_database.db:/app/bot_database.db:rw
      - ./youtube_cookies.txt:/app/youtube_cookies.txt
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"